In [7]:
#http://open.canada.ca/data/en/dataset/98f1a129-f628-4ce4-b24d-6f16bf24dd64
import pandas as pd
import numpy as np
df = pd.read_csv('cars.csv', encoding = 'ISO-8859-1')
df.head()

,YEAR,Make,Model,Size,(kW),Unnamed: 5,TYPE,CITY (kWh/100 km),HWY (kWh/100 km),COMB (kWh/100 km),CITY (Le/100 km),HWY (Le/100 km),COMB (Le/100 km),(g/km),RATING,(km),TIME (h)
0,2012,MITSUBISHI,i-MiEV,SUBCOMPACT,49,A1,B,16.9,21.4,18.7,1.9,2.4,2.1,0,NaN,100,7
1,2012,NISSAN,LEAF,MID-SIZE,80,A1,B,19.3,23.0,21.1,2.2,2.6,2.4,0,NaN,117,7
2,2013,FORD,FOCUS ELECTRIC,COMPACT,107,A1,B,19.0,21.1,20.0,2.1,2.4,2.2,0,NaN,122,4
3,2013,MITSUBISHI,i-MiEV,SUBCOMPACT,49,A1,B,16.9,21.4,18.7,1.9,2.4,2.1,0,NaN,100,7
4,2013,NISSAN,LEAF,MID-SIZE,80,A1,B,19.3,23.0,21.1,2.2,2.6,2.4,0,NaN,117,7

In [5]:
df[df['Make'] == 'TESLA']

,YEAR,Make,Model,Size,(kW),Unnamed: 5,TYPE,CITY (kWh/100 km),HWY (kWh/100 km),COMB (kWh/100 km),CITY (Le/100 km),HWY (Le/100 km),COMB (Le/100 km),(g/km),RATING,(km),TIME (h)
7,2013,TESLA,MODEL S (40 kWh battery),FULL-SIZE,270,A1,B,22.4,21.9,22.2,2.5,2.5,2.5,0,NaN,224,6
8,2013,TESLA,MODEL S (60 kWh battery),FULL-SIZE,270,A1,B,22.2,21.7,21.9,2.5,2.4,2.5,0,NaN,335,10
9,2013,TESLA,MODEL S (85 kWh battery),FULL-SIZE,270,A1,B,23.8,23.2,23.6,2.7,2.6,2.6,0,NaN,426,12
10,2013,TESLA,MODEL S PERFORMANCE,FULL-SIZE,310,A1,B,23.9,23.2,23.6,2.7,2.6,2.6,0,NaN,426,12
17,2014,TESLA,MODEL S (60 kWh battery),FULL-SIZE,225,A1,B,22.2,21.7,21.9,2.5,2.4,2.5,0,NaN,335,10
18,2014,TESLA,MODEL S (85 kWh battery),FULL-SIZE,270,A1,B,23.8,23.2,23.6,2.7,2.6,2.6,0,NaN,426,12
19,2014,TESLA,MODEL S PERFORMANCE,FULL-SIZE,310,A1,B,23.9,23.2,23.6,2.7,2.6,2.6,0,NaN,426,12
28,2015,TESLA,MODEL S (60 kWh battery),FULL-SIZE,283,A1,B,22.2,21.7,21.9,2.5,2.4,2.5,0,NaN,335,10
29,2015,TESLA,MODEL S (70 kWh battery),FULL-SIZE,283,A1,B,23.8,23.2,23.6,2.7,2.6,2.6,0,NaN,377,12
30,2015,TESLA,MODEL S (85/90 kWh battery),FULL-SIZE,283,A1,B,23.8,23.2,23.6,2.7,2.6,2.6,0,NaN,426,12
31,2015,TESLA,MODEL S 70D,FULL-SIZE,280,A1,B,20.8,20.6,20.7,2.3,2.3,2.3,0,NaN,386,12
32,2015,TESLA,MODEL S 85D/90D,FULL-SIZE,280,A1,B,22.0,19.8,21.0,2.5,2.2,2.4,0,NaN,435,12
33,2015,TESLA,MODEL S P85D/P90D,FULL-SIZE,515,A1,B,23.4,21.5,22.5,2.6,2.4,2.5,0,NaN,407,12
43,2016,TESLA,MODEL S (60 kWh battery),FULL-SIZE,283,A1,B,22.2,21.7,21.9,2.5,2.4,2.5,0,10.0,335,10
44,2016,TESLA,MODEL S (70 kWh battery),FULL-SIZE,283,A1,B,23.8,23.2,23.6,2.7,2.6,2.6,0,10.0,377,12
45,2016,TESLA,MODEL S (85/90 kWh battery),FULL-SIZE,283,A1,B,23.8,23.2,23.6,2.7,2.6,2.6,0,10.0,426,12
46,2016,TESLA,MODEL S 70D,FULL-SIZE,386,A1,B,20.8,20.6,20.7,2.3,2.3,2.3,0,10.0,386,12
47,2016,TESLA,MODEL S 85D/90D,FULL-SIZE,386,A1,B,22.0,19.8,21.0,2.5,2.2,2.4,0,10.0,435,12
48,2016,TESLA,MODEL S 90D (Refresh),FULL-SIZE,386,A1,B,20.8,19.7,20.3,2.3,2.2,2.3,0,10.0,473,12
49,2016,TESLA,MODEL S P85D/P90D,FULL-SIZE,568,A1,B,23.4,21.5,22.5,2.6,2.4,2.5,0,10.0,407,12
50,2016,TESLA,MODEL S P90D (Refresh),FULL-SIZE,568,A1,B,22.9,21.0,22.1,2.6,2.4,2.5,0,10.0,435,12
51,2016,TESLA,MODEL X 90D,SUV - STANDARD,386,A1,B,23.2,22.2,22.7,2.6,2.5,2.6,0,10.0,414,12
52,2016,TESLA,MODEL X P90D,SUV - STANDARD,568,A1,B,23.6,23.3,23.5,2.7,2.6,2.6,0,10.0,402,12

In [8]:
# compare make vs the year (in terms of battery capacity)
df.pivot_table(values='(kW)', index='YEAR', columns='Make', aggfunc=np.mean)

# results: we see that most vendors don't have a change in battery capacity over the years, except for Tesla, 
# as they've introduced several new models.

Make    BMW  CHEVROLET   FORD   KIA  MITSUBISHI  NISSAN  SMART       TESLA
YEAR
2012    NaN        NaN    NaN   NaN        49.0    80.0    NaN         NaN
2013    NaN        NaN  107.0   NaN        49.0    80.0   35.0  280.000000
2014    NaN      104.0  107.0   NaN        49.0    80.0   35.0  268.333333
2015  125.0      104.0  107.0  81.0        49.0    80.0   35.0  320.666667
2016  125.0      104.0  107.0  81.0        49.0    80.0   35.0  409.700000

In [9]:
df.pivot_table(values='(kW)', index='YEAR', columns='Make', aggfunc=[np.mean,np.min], margins=True)

       mean                                                             \
Make    BMW CHEVROLET   FORD   KIA MITSUBISHI NISSAN SMART       TESLA
YEAR
2012    NaN       NaN    NaN   NaN       49.0   80.0   NaN         NaN
2013    NaN       NaN  107.0   NaN       49.0   80.0  35.0  280.000000
2014    NaN     104.0  107.0   NaN       49.0   80.0  35.0  268.333333
2015  125.0     104.0  107.0  81.0       49.0   80.0  35.0  320.666667
2016  125.0     104.0  107.0  81.0       49.0   80.0  35.0  409.700000
All   125.0     104.0  107.0  81.0       49.0   80.0  35.0  345.478261

                   amin                                                        \
Make         All    BMW CHEVROLET   FORD   KIA MITSUBISHI NISSAN SMART  TESLA
YEAR
2012   64.500000    NaN       NaN    NaN   NaN       49.0   80.0   NaN    NaN
2013  158.444444    NaN       NaN  107.0   NaN       49.0   80.0  35.0  270.0
2014  135.000000    NaN     104.0  107.0   NaN       49.0   80.0  35.0  225.0
2015  181.428571  125.0     104.0  107.0  81.0       49.0   80.0  35.0  280.0
2016  252.263158  125.0     104.0  107.0  81.0       49.0   80.0  35.0  283.0
All   190.622642  125.0     104.0  107.0  81.0       49.0   80.0  35.0  225.0


Make All
YEAR
2012  49
2013  35
2014  35
2015  35
2016  35
All   35